# Generated by Django 3.2.6 on 2022-02-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usercreation', '0003_alter_campaigns_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_super_teacher',
            field=models.BooleanField(default=True),
        ),
    ]
