# Generated by Django 3.2.6 on 2022-02-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usercreation', '0004_auto_20220223_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='oganiztioncontroller',
        ),
        migrations.RemoveField(
            model_name='users',
            name='organization_admin',
        ),
    ]
