# Generated by Django 3.2.6 on 2022-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usercreation', '0006_auto_20220223_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_super_teacher',
        ),
        migrations.AlterField(
            model_name='users',
            name='oganiztioncontroller',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='organization_admin',
            field=models.BooleanField(default=True),
        ),
    ]
