# Generated by Django 3.2.6 on 2022-02-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usercreation', '0007_auto_20220223_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='oganiztioncontroller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='organization_admin',
            field=models.BooleanField(default=False),
        ),
    ]
